services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/appuser/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_URL=${DATABASE_URL}
      - DJANGO_SETTINGS_MODULE=transaction_audit.settings
    networks:
      - app_network

  nginx:
    image: nginx:1.21-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/home/appuser/app/static
    depends_on:
      - web
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: 