# Generated by Django 5.1.6 on 2025-02-22 13:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'merchant'], name='myapp_trans_status_7fc3d1_idx'),
        ),
    ]
